---
- hosts: Redhat
  become: yes
  tasks:
  - name: stop the service
    service: 
      name: nginx
      state: stopped
      enabled: no  
  - name: remove nginx
    yum:
     name: nginx
     state: absent
